Vagrant.configure("2") do |config|
  config.vm.define "vm-rockylinux" do |rockylinux|
    rockylinux.vm.box = "rockylinux/8"
    rockylinux.hostname = "vm-rockylinux"
	  rockylinux.vm.network "private_network", ip: "192.168.0.200"
	  rockylinux.vm.provider "virtualbox" do |vb|
    vb.memory = "2048
    end
  end
end